services:
  joypad:
    image: ras4robo:0.1
    volumes:
      - .:/Ras4Robo
    devices:
      - /dev/input/js0:/dev/input/js0
    network_mode: "host"
    command: /Ras4Robo/mqttjoypad.py
    restart: always
    depends_on:
      - drive
  drive:
    image: ras4robo:0.1
    volumes:
      - .:/Ras4Robo
    network_mode: "host"
    command: /Ras4Robo/mqttdrive.py
    restart: always
    depends_on:
      - mqttbroker
  lidar:
    image: ras4robo:0.1
    volumes:
      - .:/Ras4Robo
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: "host"
    command: /Ras4Robo/mqttlidar.py
    restart: always
    depends_on:
      - mqttbroker
  mqttbroker:
    image: eclipse-mosquitto
    network_mode: host
    #ports:
    #  - 1883:1883
    #  - 9001:9001
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./var/mqtt/data:/mosquitto/data
      - ./var/mqtt/log:/mosquitto/log
    restart: always
